### ISSUE TITLE
local server

### ISSUE THREAD

**Issue by misterpropik** [gmpassos/shelf_letsencrypt#13]
hi, please tell me, we have an application with 40 thousand clients, we need the ability to run a local server on them and generate a certificate in order to connect using a web application with a phone and send data to it. Is this possible with this package?

**Comment by gmpassos** [comment]
Let's Encrypt (https://letsencrypt.org) is a public service that generates SSL certificates for public reachable domains (real domains). For each domain, it will need to point to an IP that reaches your "local" server. I don't know if this is what you want.
