### ISSUE TITLE
AOT compilation fails

### ISSUE THREAD

**Issue by lukepighetti** [gmpassos/shelf_letsencrypt#15]
Added shelf_letsencrypt to my project and now `dart compile exe lib/main.dart` fails with error 

```
Error: AOT compilation failed
Bad state: Generating AOT kernel dill failed!
```

cannot reproduce on macOS, but I can on Ubuntu linux (via digital ocean VPS)

**Comment by gmpassos** [comment]
Thank you for the report.

Could you please publish an example on GitHub? Without it, we are unable to investigate and resolve the issue.

Best regards.

**Comment by bsutton** [comment]
This sounds like a dart issue which needs to be reported to the dart team.

Delete your .darttools directory and try again then report the issue to the
dart Devs.

You can also run a dart pub clean.

**Comment by gmpassos** [comment]
Closed: no more info provided
