### ISSUE TITLE
Does  this package actually acquire and renew certs?

### ISSUE THREAD

**Issue by bsutton** [gmpassos/shelf_letsencrypt#5]
As per the title or do you need to manage that separately?

**Comment by gmpassos** [comment]
When invoking `LetsEncrypt.startSecureServer` with `requestCertificate: true` and `checkCertificate: true`, it triggers the acquisition of a new certificate if absent or expired. Refer to the [documentation](https://pub.dev/documentation/shelf_letsencrypt/latest/shelf_letsencrypt/LetsEncrypt/startSecureServer.html) for more details. It's important to note that this process occurs solely during the server's startup.

(Indeed, there is a need for updating the documentation.)

Best regards.

**Comment by bsutton** [comment]
So is there some path that would allow preemptive renewal.

I generally renew 10 days before.

It would be nice to use something like the dart Cron package to do regular
checks.

**Comment by gmpassos** [comment]
You can call:

https://pub.dev/documentation/shelf_letsencrypt/latest/shelf_letsencrypt/LetsEncrypt/checkCertificate.html

... with `requestCertificate : true`

And if it returns `okRefreshed`, you need to close the `Server` socket and re-open it.

**Comment by gmpassos** [comment]
Also see:

https://pub.dev/documentation/shelf_letsencrypt/latest/shelf_letsencrypt/LetsEncrypt/minCertificateValidityTime.html

**Comment by bsutton** [comment]
I will have a look at it.

Thanks and thanks for the package.

**Comment by gmpassos** [comment]
Please, let me know if it works well.

Any contributions in the form of documentation or examples would be greatly appreciated.

Best regards

**Comment by gmpassos** [comment]
...

https://onepub.dev 👍

**Comment by bsutton** [comment]
I'm not in love with a map of domains and emails being passed to
startSecureServer.

I'm having to dig into the example to work out what is meant to be passed.

I assume its a map of domain names as the key to domainemails as the value.

A list that takes a small class would make this more obvious and less error
prone.

I would be happy to offer up a PR with a change if its something that you
would consider.

**Comment by gmpassos** [comment]
I will be happy to review a PR. Just make it backward compatible.

Maybe `startSecureServer` (with the current parameters) should call your new function, with a better definition.

**Comment by bsutton** [comment]
Missed the compatibility statement, will add another entry point.

**Comment by bsutton** [comment]
For the moment I will leave this  link here.

The handyman project demonstrates certificate renewal use  a task scheduler that checks every hour if a cert needs to be renewed - renews the cert - and restarts the service with the new cert.

**Comment by gmpassos** [comment]
Fixed on 2.0+ version
