### ISSUE TITLE
warning on startup -

### ISSUE THREAD

**Issue by bsutton** [gmpassos/shelf_letsencrypt#7]
Have you seen this error that gets printed on startup?

../../../.pub-cache/hosted/pub.dev/x509-0.2.4/lib/src/extension.dart:45:48: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
      ASN1Parser(sequence.elements[octetIndex].contentBytes()!).nextObject(),

**Comment by gmpassos** [comment]
It's a dependency issue:

package: x509

The owner needs to adjust its code to avoid this warning:
https://github.com/appsup-dart/x509

**Comment by bsutton** [comment]
I've just up voted on his site.

**Comment by gmpassos** [comment]
Fixed a long time ago
