### ISSUE TITLE
doAcmeChallenge ignores alternate port no.

### ISSUE THREAD

**Issue by bsutton** [gmpassos/shelf_letsencrypt#8]
For my dev environment I start the server on port 8080.

The call to doACMEChallenge is failing is it builds a URL without a port number with the result that it tries to connect on port 80 and fails.

**Comment by bsutton** [comment]
This seems to be happening in acme_client getHttpDcvData

```
  HttpDcvData getHttpDcvData() {
    var keyAuthorization = getKeyAuthorizationForChallenge(VALIDATION_HTTP);
    var token = keyAuthorization!.split('.').elementAt(0);
    return HttpDcvData(
      '${identifier!.value}/.well-known/acme-challenge/$token',
      keyAuthorization,
      getChallengeByType(VALIDATION_HTTP),
    );
  }
```
the `identifier.value` has the domain name but no port no.

**Comment by bsutton** [comment]
We see the following message logged before the call is made (and fails)

Self test challenge... {type: HTTP, fileName: squarephone.biz/.well-known/acme-challenge/ksPAAcFzl5CSUQNXwymuoLcZ0NEpsGTHK00Y5AFQXRs, fileContent: ksPAAcFzl5CSUQNXwymuoLcZ0NEpsGTHK00Y5AFQXRs.wZQeeUT1GoiIsb-N7YRgyTccyL7GBnF_QfeYc6w2rVc, challenge: Instance of 'Challenge'

**Comment by bsutton** [comment]
So I think the problem is here:

```
Future<bool> _selfChallengeTest(
      AcmeClient client, HttpDcvData challengeData) async {
    var url = challengeData.fileName;
    if (!url.startsWith('http:') && !url.startsWith('https:')) {
      final idx = url.indexOf(':/');
      if (idx >= 0) {
        final schema = url.substring(0, idx);
        var rest = url.substring(idx);
        rest = rest.replaceFirst(RegExp('^/+'), '');
        url = '$schema://${rest.replaceAll('//', '/')}';
      } else {
        final rest = url.replaceFirst(RegExp('^/+'), '');
        url = 'http://${rest.replaceAll('//', '/')}';
      }
    }

```

We are pre-pending HTTP:// but we ignore the need to add in the port.

**Comment by bsutton** [comment]
I will see if I can fix it.

**Comment by bsutton** [comment]
I have a fix for it, it does mean passing the httpPort around  quite a bit.

**Comment by gmpassos** [comment]
Did you post an issue there?

**Comment by gmpassos** [comment]
The issue is only on `shelf_letsencrypt`?

**Comment by bsutton** [comment]
The bug was on shelf_letsenctypt, I've fixed it.

**Comment by gmpassos** [comment]
Nice 👍

Since your PR includes a lot of improvements, I will take a few days to review all of the code and make adjustments on my machine.

Additionally, considering your significant contribution, please include your name and GitHub page in the "Author" section.

**Comment by bsutton** [comment]
Thank you, I will do that.

Fyi: in raising a pr to give the acme_client bug.

**Comment by gmpassos** [comment]
...Also, I will need to test it in the staging environment of some internal projects that are using `shelf_letsencrypt`.

**Comment by bsutton** [comment]
Sound good, key me know if I've broken anything:)

**Comment by bsutton** [comment]
So this looks to be a bigger issue.
Anywhere we do a call back to the local server the code is broken because it ignores the current port.

Worry the current api the porr isn't known until the users starts the server but we have a number methods that are valid independently of starting the server.

It kids to be like we need to move the port and bind address to the letsencrpt constructor.

This would be a breaking change but I think it's the right way to do it.

Thoughts?

**Comment by gmpassos** [comment]
Example of an error in the RFC without an status:

```text
HTTP/1.1 403 Forbidden
Content-Type: application/problem+json
Link: <https://example.com/acme/directory>;rel="index"

{
    "type": "urn:ietf:params:acme:error:malformed",
    "detail": "Some of the identifiers requested were rejected",
    "subproblems": [
        {
            "type": "urn:ietf:params:acme:error:malformed",
            "detail": "Invalid underscore in DNS name \"_example.org\"",
            "identifier": {
                "type": "dns",
                "value": "_example.org"
            }
        },
        {
            "type": "urn:ietf:params:acme:error:rejectedIdentifier",
            "detail": "This CA will not issue for \"example.net\"",
            "identifier": {
                "type": "dns",
                "value": "example.net"
            }
        }
    ]
}
```

**Comment by gmpassos** [comment]
The point is that `LetsEncrypt` should be able to handle multiple domains in the same address:port.

The custom port is only needed for the HTTP challenge?
If it's true, it knows the listening port of the HTTP server that it started. (should be inserted in the HTTP URL only if it's different than 80).

**Comment by bsutton** [comment]
> The point is that LetsEncrypt should be able to handle multiple domains in the same address:port.
I don't believe that I've made any changes to inhibit this. Have you raised this due to a concern or problem?

> The custom port is only needed for the HTTP challenge?

I had to make changes in two spots:
- _selfChallengeTest
- isDomainHttpsOk
So the custom port details were required for both HTTP and https.

> should be inserted in the HTTP URL only if it's different than 80).
I've been a little lazy by always inserting the port. It's essentially invisible to the user and valid so I don't really see the issue. If you want I can make it conditional?

**Comment by gmpassos** [comment]
Make the changes. I don't think they will be backward incompatible.

**Comment by bsutton** [comment]
I think I've now made all the changes I'm going to, so go ahead and merge
if you are happy with everything.

**Comment by gmpassos** [comment]
Do you want to make any new adjustment or wait some dependency fix/patch?

**Comment by bsutton** [comment]
I'm all done.

**Comment by bsutton** [comment]
Fixed via:
https://github.com/gmpassos/shelf_letsencrypt/pull/6
